title: just sit and grin
url: "https://dive.github.io"
# baseurl: "https://dive.github.io"
show_downloads: "false"
author:
  name: Artem Loenko
  twitter: justsitandgrin
twitter_username: justsitandgrin
github_username:  dive
google_site_verification: 1Q_iYF2ITP7uIHU-6z-iwgENozyKDdNMeH2GYeOmejM 

github_comments_repository: dive/dive.github.io

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
