title: just sit and grin
url: "https://dive.github.io"
# baseurl: "https://dive.github.io"
show_downloads: "false"
twitter_username: justsitandgrin
github_username:  dive

github_comments_repository: dive/dive.github.io

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
